const pool = require("../db/db");
const compileQuery = require("../services/queryCompiler");
const validateDsl = require("../services/dslSchema");
const { parseEnglishToRules } = require("../services/aiRuleParser");

/**
 * 1️⃣ Fetch all stocks
 * GET /api/stocks
 */
const getAllStocks = async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT 
        symbol,
        company_name,
        ROUND(current_price::numeric, 2) AS current_price,
        ROUND(pe_ratio::numeric, 2) AS pe_ratio,
        ROUND(market_cap::numeric, 0) AS market_cap
      FROM stocks
      ORDER BY symbol ASC
    `);

    res.status(200).json({
      count: result.rows.length,
      data: result.rows,
    });

  } catch (error) {
    console.error("Error fetching stocks:", error.message);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * 2️⃣ Basic Screener
 * GET /api/stocks/screener
 */
const screenStocks = async (req, res) => {
  try {

    const { pe, price, marketCap } = req.query;

    let query = `
      SELECT 
        symbol,
        company_name,
        ROUND(current_price::numeric, 2) AS current_price,
        ROUND(pe_ratio::numeric, 2) AS pe_ratio,
        ROUND(market_cap::numeric, 0) AS market_cap
      FROM stocks
      WHERE 1=1
    `;

    const values = [];
    let index = 1;

    if (pe) {
      query += ` AND pe_ratio <= $${index++}`;
      values.push(pe);
    }

    if (price) {
      query += ` AND current_price <= $${index++}`;
      values.push(price);
    }

    if (marketCap) {
      query += ` AND market_cap >= $${index++}`;
      values.push(marketCap);
    }

    query += " ORDER BY pe_ratio ASC";

    const result = await pool.query(query, values);

    res.status(200).json({
      count: result.rows.length,
      data: result.rows,
    });

  } catch (error) {
    console.error("Error screening stocks:", error.message);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * 3️⃣ Manual Screener
 * POST /api/stocks/manual-screener
 */
const manualScreener = async (req, res) => {

  try {

    const { pe_ratio } = req.body;

    let query = `
      SELECT 
        symbol,
        company_name,
        sector,
        current_price,
        pe_ratio,
        peg_ratio,
        market_cap,
        revenue_growth,
        ebitda_growth,
        debt_to_fcf,
        volume
      FROM stocks
      WHERE 1=1
    `;

    const values = [];
    let index = 1;

    if (pe_ratio) {
      query += ` AND pe_ratio <= $${index++}`;
      values.push(pe_ratio);
    }

    query += ` ORDER BY pe_ratio ASC`;

    const result = await pool.query(query, values);

    res.status(200).json({
      success: true,
      count: result.rows.length,
      data: result.rows
    });

  } catch (error) {

    console.error("Manual Screener Error:", error.message);

    res.status(500).json({
      success: false,
      message: "Manual screener failed"
    });

  }
};

/**
 * 4️⃣ AI Screener
 * POST /api/stocks/ai-screener
 */
const screenStocksAI = async (req, res) => {

  try {

    const { query: userQuery } = req.body;

    if (!userQuery) {
      return res.status(400).json({
        success: false,
        message: "Query text is required"
      });
    }

    // 1️⃣ English → DSL
    const dsl = await parseEnglishToRules(userQuery);

    // 2️⃣ Validate DSL using AJV
    const isValid = validateDsl(dsl);

    if (!isValid) {
      console.error("DSL validation error:", validateDsl.errors);

      return res.status(400).json({
        success: false,
        message: "Invalid DSL generated by AI",
        errors: validateDsl.errors
      });
    }

    // 3️⃣ DSL → SQL
    const { query, values } = compileQuery(dsl);

    const result = await pool.query(query, values);

    res.status(200).json({
      success: true,
      filtersApplied: dsl,
      count: result.rows.length,
      data: result.rows
    });

  } catch (error) {

    console.error("AI Screener Error:", error.message);

    res.status(500).json({
      success: false,
      message: error.message
    });

  }
};

module.exports = {
  getAllStocks,
  screenStocks,
  screenStocksAI,
  manualScreener
};