from typing import Dict, Any

# --- 1. DISCLAIMER TEXTS ---
DISCLAIMERS = {
    "global_banner": """
        🚧 **EDUCATIONAL PROTOTYPE:** This platform is for academic purposes only. 
        **Do not trade real money based on these results.**
    """,
    "global_footer": """
        © 2026 AI Screener Project. All investment strategies involve risk of loss. 
        Nothing contained in this website should be construed as investment advice. 
        Data source: Mock/Historical data only.
    """,
    "screener_results": """
        📉 **Data Accuracy Notice:** These results are generated by a machine learning model filtering historical data. 
        The presence of a stock in this list is **not a recommendation to buy**.
    """,
    "analyst_risk": """
        🎯 **Third-Party Analyst Disclaimer:** Analyst ratings and Target Prices are subjective opinions from external sources. 
        They are often wrong. **Never invest solely based on an analyst rating.**
    """,
    "alerts_trigger": """
        🔔 **Alert Reliability:** Alerts are triggered based on periodic snapshots, not real-time ticks. 
        Execution delays may occur.
    """
}

# --- 2. ADVISORY KEYWORDS (Forbidden Words) ---
ADVISORY_KEYWORDS = [
    "buy now", "sell now", "guarantee", "sure shot", 
    "target price", "strong buy", "strong sell", 
    "invest in this", "crypto", "gambling", 
    "100% return", "safe bet"
]

# --- 3. HELPER FUNCTIONS ---

def get_disclaimer(key: str) -> str:
    """Fetches the disclaimer text."""
    return DISCLAIMERS.get(key, DISCLAIMERS["global_footer"])

def check_compliance(query: str) -> bool:
    """
    Returns False if the query contains forbidden advisory language.
    """
    if not query:
        return True
    query_lower = query.lower()
    for word in ADVISORY_KEYWORDS:
        if word in query_lower:
            return False
    return True

def standardize_error(status_code: int) -> Dict[str, Any]:
    """
    Returns a safe, generic error message to hide internal system details.
    """
    if status_code == 400:
        return {"error": "Invalid Request", "message": "Your query could not be processed. Please refine your input."}
    elif status_code == 401:
        return {"error": "Unauthorized", "message": "Access denied. Please login again."}
    elif status_code == 404:
        return {"error": "Not Found", "message": "The requested resource is unavailable."}
    elif status_code == 409:
        return {"error": "Conflict", "message": "This resource already exists."}
    elif status_code == 422:
        return {"error": "Validation Error", "message": "The provided data format is incorrect."}
    else:
        # Default 500 (Hide Stack Trace)
        return {"error": "System Error", "message": "An internal service interruption occurred. Support has been notified."}